BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_DIR = /opt/Arduino/arduino-1.8.5/
ARDMK_DIR = /opt/Arduino/arduino-mk
AVRDUDE_CONF = /etc/avrdude.conf

include /opt/Arduino/arduino-mk/Arduino.mk
