BOARD_TAG   = nano
BOARD_SUB   = atmega328old
MONITOR_BAUDRATE  = 115200
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_DIR = ./arduino-1.8.8
ARDMK_DIR = ./Arduino-Makefile
AVRDUDE_CONF = /etc/avrdude.conf

include ./Arduino-Makefile/Arduino.mk